### ISSUE TITLE
Build on OS X 10.9.2 fails: fixed with change to WARNING_CXXFLAGS

### ISSUE THREAD

**Issue by acarabott** [OpenLightingProject/ola#358]
Building on OS X 10.9.2 with default settings failed at three places:

```
StrUtil.cpp:294:21: error: unused function 'PlaceNum' [-Werror,-Wunused-function]

ola-dmxmonitor.cpp:63:28: error: unused variable 'CHANNEL_NUDGE_VALUE' [-Werror,-Wunused-const-variable] 
static const unsigned char CHANNEL_NUDGE_VALUE = 0x10;

ExceptionTestCaseDecorator.h:95:55: error: unused parameter 'e' [-Werror,-Wunused-parameter]
```

  virtual void checkException( ExpectedExceptionType &e )

Managed to deal with this by adding the following to `WARNING_CXXFLAGS` in `common.mk`

```
-Wno-unused-function \
-Wno-unused-const-variable \
-Wno-unused-parameter \
```
### Compiler info:

```
$ gcc --version
$ g++ --version 

Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix
```
