### ISSUE TITLE
pip installs v0.10.7, which doesn't work in python3.13

### ISSUE THREAD

**Issue by rbalykov** [OpenLightingProject/ola#2029]
File "/home/oscar/devel/dmxrec/.venv/lib/python3.13/site-packages/google/protobuf/service_reflection.py", line 182, in _CallMethod
    return method(rpc_controller, request, callback)
  File "/home/oscar/devel/dmxrec/.venv/lib/python3.13/site-packages/ola/OlaClient.py", line 1095, in UpdateDmxData
    data.fromstring(request.data)
    ^^^^^^^^^^^^^^^
AttributeError: 'array.array' object has no attribute 'fromstring'

Conclusion: update API on PIP site

**Comment by peternewman** [comment]
What OS are you on and how did you install OLA @rbalykov ?

https://pypi.org/project/ola/

We've not traditionally released to pip as part of our release process, or we'd risk spending the whole time releasing for different platforms we support and not writing code!

Paging @sul3n3t who did the last pip release.

**Comment by rbalykov** [comment]
> What OS are you on and how did you install OLA [@rbalykov](https://github.com/rbalykov) ?

Debian, Python 3.13, but it doesn't make sence, the latest release on pypi is 10.7

> We've not traditionally released to pip as part of our release process

I found out how to satisfy pip with local package.

**Comment by peternewman** [comment]
I'm going to close this as a duplicate, as it's covered in #1451 .

But if you're on Debian, are you also aware there is `ola-python` which will do the same thing and ensure you Python flavoured OLA is in line with your OS OLA.

> I found out how to satisfy pip with local package.

Would you care to detail that for the next person who comes along?

**Comment by rbalykov** [comment]
> Would you care to detail that for the next person who comes along?

.venv projects use only pip and requirements.txt
Installed .py files should be pip package.
It starts with pyproject.toml, then 'python -m build', it makes .whl and .tar.gz, which comes to requirements.txt
Voilà, here you go.

Here are files made by me, .whl is gzipped because github doesn't upload .whl
[ola-0.10.9.tar.gz](https://github.com/user-attachments/files/27443069/ola-0.10.9.tar.gz)
[ola-0.10.9-py3-none-any.whl.gz](https://github.com/user-attachments/files/27443095/ola-0.10.9-py3-none-any.whl.gz)
