### ISSUE TITLE
QLC+ OLA plugin build issue

### ISSUE THREAD

**Issue by mcallegari** [OpenLightingProject/ola#657]
Hi guys, just received a new Mac today with OSX 10.10.2, XCode 6.1.1
Got OLA 0.9.5 from macports

The build process of QLC+ stops at the OLA plugin with this error:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -single_module -dynamiclib -o libolaio.dylib olaio.o olaoutthread.o configureolaio.o qlclogdestination.o moc_qlcioplugin.o moc_olaio.o moc_configureolaio.o  -F/Users/massimo/Qt5.4.1/5.4/clang_64/lib -L/opt/local/lib -lolaserver -lola -lolacommon -lprotobuf -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL  
Undefined symbols for architecture x86_64:
  "ola::StringTrim(std::string*)", referenced from:
      ola::QLCLogDestination::Write(ola::log_level, std::string const&) in qlclogdestination.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libolaio.dylib] Error 1
make[1]: *** [sub-ola-make_first] Error 2
make: *** [sub-plugins-make_first-ordered] Error 2

Apparently the ola::StringTrim method is not there anymore ?
Can you please confirm that and in case suggest a proper fix including backward compatibility ?

Thanks

**Comment by peternewman** [comment]
Hi, it's still there:
https://github.com/OpenLightingProject/ola/blob/master/include/ola/StringUtils.h#L75
And here:
https://github.com/OpenLightingProject/ola/blob/master/common/utils/StringUtils.cpp#L60

Do you know when QLC+ last built successfully with it?

**Comment by mcallegari** [comment]
Yeah I double checked and I couldn't explain that.
I believe it was fine on 0.9.2. I could check on my old OSX installation.

I've got an update. When commenting StringTrim, the plugin builds fine, but when it is loaded by QLC+ it fires an unpleasant segfault.
Log here: http://pastebin.com/mFmAUw3S

There seems to be something around ola/Logging but I can't figure it out myself.

**Comment by mcallegari** [comment]
In my previous OSX (10.8.2) installation I had OLA 0.9.1 and it was working fine

**Comment by mcallegari** [comment]
Another update: I built OLA 0.9.5 myself from sources and got the same results.
Gonna try with 0.9.4 now.

**Comment by mcallegari** [comment]
At last, I tried to build on OLA 0.9.1. Same error.
I searched for the issue on Google and found that the -mmacosx-version-min flag does the trick. It was set to 10.7. Setting it to 10.9 magically solves the build issue.
I remember I had to do it in the past but never understood what that meant.
Does it mean that the OLA plugin can be used only on OSX 10.9 and above ?
Also, why do I have this restriction only for OLA ? All the rest of the QLC+ builds fine with -mmacosx-version-min=10.7. Any idea ?

Thanks

**Comment by stephanmg** [comment]
Maybe OLA 0.9.1 needs at a minimum 10.9?

**Comment by nomis52** [comment]
That's really odd. I'm at a loss to explain this. Can you post the link you found?

**Comment by mcallegari** [comment]
Sure, here it is
https://forum.qt.io/topic/35065/solved-qt5-1-qt5-2-xcode-5-0-2-mac-os-10-9-mavericks-can-t-link-to-the-libraries-undefined-symbols-for-architecture-x86_64

I think it happens on a Qt project, but as I said I experienced it only with OLA and not with any of the other libraries I link: libftdi, liblo, libmad, libsndfile, libusb, etc
Really weird indeed.

**Comment by nomis52** [comment]
Actually now this all rings a bell! I've had this problem before when trying to link Qt programs with OLA. See the links at the end of https://github.com/nomis52/sACNDiscovery 

In particular:

https://blog.inventic.eu/2014/01/qt-on-osx-maverick-undefined-symbols-for-architecture-x86_64/

"The problem is that starting with OSX 10.9 Apple changed default standard c++ library from libstdc++ to libc++."

**Comment by mcallegari** [comment]
And Apple strikes again (after the horrible FTDI driver surprise) ! :smile:
What I am wondering is if this 10.9 requirement breaks backward compatibility. (e.g. not working on 10.8)
The more Qt advances, the less they support old OSX versions. I think with Qt 5.5 they're gonna require OSX 10.7.

Anyway, feel free to close this ticket :+1:
