### PR TITLE
Fix the build on Ubuntu 14.04

### LINKED ISSUE #650: build fails on ubuntu 14.04.1 "TrustyThar"
also on the [buildbot](https://buildbot.openlighting.org/builders/buildcheck-ola-ubuntu-tahr-i686-noopenslp/builds/1581/steps/make/logs/stdio)
build log:
```bash
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -I/usr/include/libusb-1.0   -g -O2 -pthread -MT plugins/usbdmx/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.lo -MD -MP -MF plugins/usbdmx/.deps/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.Tpo -c -o plugins/usbdmx/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.lo `test -f 'plugins/usbdmx/AsyncPluginImpl.cpp' || echo './'`plugins/usbdmx/AsyncPluginImpl.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -I/usr/include/libusb-1.0 -g -O2 -pthread -MT plugins/usbdmx/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.lo -MD -MP -MF plugins/usbdmx/.deps/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.Tpo -c plugins/usbdmx/AsyncPluginImpl.cpp  -fPIC -DPIC -o plugins/usbdmx/.libs/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.o
plugins/usbdmx/AsyncPluginImpl.cpp: In member function 'virtual bool ola::plugin::usbdmx::AsyncPluginImpl::Start()':
plugins/usbdmx/AsyncPluginImpl.cpp:98:28: error: expected type-specifier before 'LibUsbHotplugThread'
     m_usb_thread.reset(new LibUsbHotplugThread(
                            ^
make[2]: *** [plugins/usbdmx/plugins_usbdmx_libolausbdmx_la-AsyncPluginImpl.lo] Error 1
```

### PR DESCRIPTION
**Pull request by peternewman**
Final retrospective (hopefully) @nomis52 .

On 14.04 libusb-1.0-0-dev defines LIBUSBX_API_VERSION rather than LIBUSB_API_VERSION.

Should close #650

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM
